### ISSUE TITLE
Losing timer cycles on div overflow

### ISSUE THREAD

**Issue by izik1** [DannyGlover/cBoy#1]
https://github.com/DannyGlover/cBoy/blob/6cbc1c200d15ac79ebecddd1581277eba14dccf2/timer.cpp#L61-L75
Say when you call the function you have `DividerCounter == 252` and `clockCycles == 8`
`DividerCounter += clockCycles;` -> `DividerCounter = 252 + 8` -> `DividerCounter = 260`

`if (DividerCounter > 255)` -> `if (260 > 255)` -> `if (true)`
`DividerCounter = 0;` -> `DividerCounter = 260 - 260` the divider writes to the upper bits every 256 ticks, so this is incorrect (those 4 cycles get lost)

**Comment by DannyGlover** [comment]
:)

Fixed in #0d0818090f3ae628422f6eff6f46bd413c2c47a2

**Comment by DannyGlover** [comment]
:)

Fixed in 0d0818090f3ae628422f6eff6f46bd413c2c47a2

**Comment by izik1** [comment]
Closed as fixed
